# Generated by Django 4.1.4 on 2023-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('likes', models.IntegerField()),
                ('image', models.ImageField(upload_to='blog/images')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('plan', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='plan/images')),
            ],
        ),
    ]
