# Generated by Django 4.1.4 on 2023-01-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.TextField(),
        ),
    ]
