# Generated by Django 4.1.4 on 2023-01-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
